version: "3.9"

services:
  mentoark-site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mentoark-site
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      traefik.enable: "true"

      # Roteador HTTPS
      traefik.http.routers.mentoark-site.rule: Host(`${HOST}`)
      traefik.http.routers.mentoark-site.entrypoints: websecure
      traefik.http.routers.mentoark-site.tls: "true"
      traefik.http.routers.mentoark-site.tls.certresolver: letsencrypt

      # Serviço aponta para a porta interna 3000
      traefik.http.services.mentoark-site.loadbalancer.server.port: "3000"

    networks:
      - traefik

networks:
  traefik:
    external: true
