version: "3.9"

services:
  sitetech:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: mentoark/sitetech:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - TZ=America/Sao_Paulo

    networks:
      - traefik

    # saúde do container (opcional)
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:3000/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

    labels:
      traefik.enable: "true"

      # HTTPS (principal)
      traefik.http.routers.sitetech.rule: "Host(`site.mentoark.com.br`)"
      traefik.http.routers.sitetech.entrypoints: "websecure"
      traefik.http.routers.sitetech.tls: "true"
      traefik.http.routers.sitetech.tls.certresolver: "letsencrypt"

      # serviço interno (porta do Next no container)
      traefik.http.services.sitetech.loadbalancer.server.port: "3000"

      # HTTP -> HTTPS
      traefik.http.routers.sitetech-web.rule: "Host(`site.mentoark.com.br`)"
      traefik.http.routers.sitetech-web.entrypoints: "web"
      traefik.http.routers.sitetech-web.middlewares: "sitetech-redirect"
      traefik.http.middlewares.sitetech-redirect.redirectscheme.scheme: "https"

networks:
  traefik:
    external: true
